name: Variety
version: '1.0-SNAPSHOT'
main: me.matty.variety.Main
api-version: 1.18
authors: [ Matty ]
description: May do a variety of things.
commands:
  dropperplace:
    description: Dropper gets placed.
    usage: /<command>
  dropperremove:
    description: Dropper gets removed.
    usage: /<command>
  droppergetdroplet:
    description: Droplet(s) achieved.
    usage: /<command>
